#!/bin/bash

function gen_pwd_char() {
    s=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890-_%/
    # Length of the string
    p=$(( $RANDOM % 66))
    echo -n ${s:$p:1}
}

#12-char pwd
POSTGRES_PASSWORD=`gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; gen_pwd_char; `

POSTGRES_USER=aiida
POSTGRES_DB=aiida_default
AIIDA_BACKEND=django

# TODO: To be changed/autogenerated

if [ -e sshkeys ]
then
    echo "folder sshkeys exists, remove it first"
    exit 1
fi

mkdir -p sshkeys/sharedfolder
ssh-keygen -t rsa -f sshkeys/sharedfolder/aiida_key -C "Key for Dockerized AiiDA service" -N ''

# To allow to read it from inside the docker container, I make the 
# private key readable by everybody, but I put the containing folder as
# readable only by me
chmod go= sshkeys/
chmod go=rx sshkeys/sharedfolder/
chmod go+r sshkeys/sharedfolder/aiida_key

THEKEY=`cat sshkeys/sharedfolder/aiida_key.pub`

# No need of escaping
echo 'AUTHORIZED_KEY='"$THEKEY" > env/torque.env

echo 'AIIDA_USER='"$POSTGRES_USER" > env/aiida.env
echo 'AIIDA_DB='"$POSTGRES_DB" >> env/aiida.env
echo 'AIIDA_PWD='"$POSTGRES_PASSWORD" >> env/aiida.env
echo 'AIIDA_BACKEND='"$AIIDA_BACKEND" >> env/aiida.env

echo 'POSTGRES_USER='"$POSTGRES_USER" > env/postgres.env
echo 'POSTGRES_DB='"$POSTGRES_DB" >> env/postgres.env
echo 'POSTGRES_PASSWORD='"$POSTGRES_PASSWORD" >> env/postgres.env

